#!/usr/bin/env bash
# Populate this project with the RPG Maker MZ runtime and Company Assets from
# YOUR OWN licensed installation.
#
# Nothing under img/, audio/, js/rmmz_*.js, effects/ or the deployment shell is
# in this repository, and none of it may be: it is licensed to the holder of an
# RPG Maker MZ licence and this repository is public. This script copies it in
# locally, where the licence permits it.
#
#   usage:  tools/hydrate_assets.sh /path/to/RPGMZ/NewData
#
# The source is a NewData template project, or any project you created in the
# editor. Typical locations:
#   Windows  C:\Program Files\KADOKAWA\RPGMZ\NewData
#   Steam    .../steamapps/common/RPG Maker MZ/NewData
#   macOS    /Applications/RPG Maker MZ.app/Contents/Resources/app.nw/NewData
set -euo pipefail

SRC="${1:-}"
DEST="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -z "$SRC" ]]; then
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 2
fi
if [[ ! -d "$SRC" ]]; then
  echo "error: '$SRC' is not a directory" >&2
  exit 1
fi
if [[ ! -f "$SRC/js/rmmz_core.js" ]]; then
  echo "error: '$SRC' does not look like an RPG Maker MZ project (no js/rmmz_core.js)." >&2
  echo "       Point this at a NewData template or a project you made in the editor." >&2
  exit 1
fi

echo "Hydrating Gray Stone from: $SRC"
echo

# 1. Core runtime -------------------------------------------------------------
mkdir -p "$DEST/js/libs"
for f in rmmz_core.js rmmz_managers.js rmmz_objects.js rmmz_scenes.js rmmz_sprites.js rmmz_windows.js main.js; do
  if [[ -f "$SRC/js/$f" ]]; then
    cp -f "$SRC/js/$f" "$DEST/js/$f"
    echo "  js/$f"
  else
    echo "  !! missing in source: js/$f" >&2
  fi
done
[[ -d "$SRC/js/libs" ]] && cp -rf "$SRC/js/libs/." "$DEST/js/libs/" && echo "  js/libs/"

# NOTE: js/plugins.js is OURS -- it lists the Gray Stone plugins. Never overwrite it.
echo "  (js/plugins.js kept: it is project source, not a Company Asset)"

# 2. Art and audio ------------------------------------------------------------
for d in img audio effects fonts icon movies; do
  if [[ -d "$SRC/$d" ]]; then
    mkdir -p "$DEST/$d"
    cp -rf "$SRC/$d/." "$DEST/$d/"
    echo "  $d/  ($(find "$DEST/$d" -type f | wc -l | tr -d ' ') files)"
  fi
done

# 3. Deployment shell ---------------------------------------------------------
for f in index.html package.json; do
  [[ -f "$SRC/$f" ]] && cp -f "$SRC/$f" "$DEST/$f" && echo "  $f"
done

# 4. Project file -------------------------------------------------------------
# The .rmmzproject file is just a version marker; recreate rather than copy so
# the project opens under its own name.
if [[ ! -f "$DEST/game.rmmzproject" ]]; then
  if [[ -f "$SRC/game.rmmzproject" ]]; then
    cp -f "$SRC/game.rmmzproject" "$DEST/game.rmmzproject"
  else
    echo "RPGMZ 1" > "$DEST/game.rmmzproject"
  fi
  echo "  game.rmmzproject"
fi

# 5. data/ is OURS -- with exactly one exception -------------------------------
# Gray Stone's database and maps are generated into data/, so the template's
# data/ must not overwrite them. Tilesets.json is the exception: it pairs the
# vendor's 8192 passability flags with the vendor's art, and the two must travel
# together. A generated stand-in leaves real trees, fences and walls walkable.
if [[ -f "$SRC/data/Tilesets.json" ]]; then
  cp -f "$SRC/data/Tilesets.json" "$DEST/data/Tilesets.json"
  echo "  data/Tilesets.json  (stock passability -- travels with the art)"
else
  echo "  !! $SRC/data/Tilesets.json not found; the project will keep synthesized flags" >&2
fi
echo "  data/ otherwise NOT copied: it is generated by 'node tools/build/index.js'"

echo
echo "Done. Next:"
echo "  node tools/build/index.js        regenerate data/ from spec/"
echo "  node tools/validate/validate.js  static checks"
echo "  node tools/verify_assets.js      confirm every referenced asset now exists"
echo "  then open the folder in RPG Maker MZ and play-test the prologue."
